name: Windows Remote Desktop (Ngrok)

on:
  workflow_dispatch:

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
    - name: üîΩ Download Ngrok & RDP Tools
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip -DestinationPath ngrok
        Invoke-WebRequest https://raw.githubusercontent.com/SahrulGunawan-ID/FREE-RDP/main/MODULE/START.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/SahrulGunawan-ID/FREE-RDP/main/MODULE/LOOP.bat -OutFile loop.bat

    - name: üß™ Debug NGROK TOKEN
      run: |
        if ($Env:NGROK_AUTH_TOKEN -eq "") {
          echo "‚ùå NGROK TOKEN NOT FOUND"
          exit 1
        } else {
          echo "‚úÖ NGROK TOKEN FOUND"
        }
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: üîê Authenticate Ngrok
      run: |
        .\ngrok\ngrok.exe config add-authtoken $Env:NGROK_AUTH_TOKEN
        .\ngrok\ngrok.exe config check
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: üîì Enable RDP & Firewall
      run: |
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 1

    - name: üë§ Set RDP User & Password
      run: |
        net user runneradmin P@ssw0rd123 /add
        net localgroup administrators runneradmin /add

    - name: ‚öôÔ∏è Start RDP Service
      run: |
        Start-Service TermService

    - name: üåê Start Ngrok Tunnel (KEEP ALIVE)
      run: |
        cd ngrok
        .\ngrok.exe tcp --region ap 3389

    - name: üîÅ Keep Runner Alive
      run: cmd /c loop.bat
